# Generated by Django 4.2.19 on 2025-12-29 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Scenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="场景名称")),
                ("epoch", models.CharField(max_length=100, verbose_name="历元时间")),
                ("start_time", models.CharField(max_length=100, verbose_name="开始时间")),
                ("end_time", models.CharField(max_length=100, verbose_name="结束时间")),
                ("alt_km", models.FloatField(verbose_name="高度(km)")),
                ("inc_deg", models.FloatField(verbose_name="倾角(度)")),
                ("n_planes", models.IntegerField(verbose_name="轨道面数量")),
                ("n_sats_per_plane", models.IntegerField(verbose_name="每轨道面卫星数")),
                (
                    "sensor_config",
                    models.JSONField(blank=True, null=True, verbose_name="传感器配置"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "场景",
                "verbose_name_plural": "场景",
                "db_table": "scenarios",
            },
        ),
        migrations.CreateModel(
            name="Satellite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sat_id", models.CharField(max_length=100, verbose_name="卫星ID")),
                ("stk_name", models.CharField(max_length=255, verbose_name="STK名称")),
                ("plane_index", models.IntegerField(verbose_name="轨道面索引")),
                ("sat_index_in_plane", models.IntegerField(verbose_name="轨道面内卫星索引")),
                ("alt_km", models.FloatField(verbose_name="高度(km)")),
                ("sma_km", models.FloatField(verbose_name="半长轴(km)")),
                ("ecc", models.FloatField(verbose_name="偏心率")),
                ("inc_deg", models.FloatField(verbose_name="倾角(度)")),
                ("raan_deg", models.FloatField(verbose_name="升交点赤经(度)")),
                ("argp_deg", models.FloatField(verbose_name="近地点幅角(度)")),
                ("ta_deg", models.FloatField(verbose_name="真近点角(度)")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="satellites",
                        to="satellites.scenario",
                        verbose_name="所属场景",
                    ),
                ),
            ],
            options={
                "verbose_name": "卫星",
                "verbose_name_plural": "卫星",
                "db_table": "satellites",
                "indexes": [
                    models.Index(
                        fields=["scenario", "sat_id"],
                        name="satellites_scenari_78d1c8_idx",
                    ),
                    models.Index(
                        fields=["plane_index", "sat_index_in_plane"],
                        name="satellites_plane_i_57b184_idx",
                    ),
                ],
            },
        ),
    ]
