# Generated by Django 4.2.19 on 2025-12-29 03:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("satellites", "0001_initial"),
    ]

    operations = [
        # 这些字段在数据库中本来就不存在，所以只更新状态，不执行数据库操作
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # 不执行任何数据库操作
            state_operations=[
                migrations.RemoveField(
                    model_name="satellite",
                    name="created_at",
                ),
                migrations.RemoveField(
                    model_name="satellite",
                    name="updated_at",
                ),
                migrations.RemoveField(
                    model_name="scenario",
                    name="created_at",
                ),
                migrations.RemoveField(
                    model_name="scenario",
                    name="updated_at",
                ),
            ],
        ),
    ]
